version: "3.8"
services:
  app:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - redis
    environment:
      APP_ENV: local
  postgres:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_DB: monthli
      POSTGRES_USER: monthli
      POSTGRES_PASSWORD: secret
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U monthli -d monthli"]
      interval: 5s
      retries: 5
  redis:
    image: redis:alpine
    restart: unless-stopped
  horizon:
    build: .
    command: php artisan horizon
    depends_on:
      - redis
      - postgres
volumes:
  postgres_data:
