version: "3.8"
services:
  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
      target: production
    depends_on:
      - postgres
      - redis
    environment:
      - APP_ENV=production
      - APP_DEBUG=false
    volumes:
      - ../storage:/var/www/storage
      - ../bootstrap/cache:/var/www/bootstrap/cache
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    depends_on:
      - app
    volumes:
      - ..:/var/www
      - ./nginx/conf.d:/etc/nginx/conf.d
    restart: unless-stopped

  postgres:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_DB: monthli
      POSTGRES_USER: monthli
      POSTGRES_PASSWORD: secret
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U monthli -d monthli"]
      interval: 5s
      retries: 5

  redis:
    image: redis:alpine
    restart: unless-stopped
    volumes:
      - redis_data:/data

  horizon:
    build: .
    command: php artisan horizon
    depends_on:
      - redis
      - postgres
    environment:
      - APP_ENV=production
      - APP_DEBUG=false
    volumes:
      - ../storage:/var/www/storage
      - ../bootstrap/cache:/var/www/bootstrap/cache
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data:
